[workspace]
resolver = "2"
members = [
    "yas",
    "yas-genshin",
    "yas-starrail",
    "yas-derive",
    "yas-application",
    "yas-wutheringwaves"
, "yas-derive-wuthering-waves"]

[profile.release]
lto = true
panic = "abort"
strip = true
